### ISSUE TITLE
Mainnet Tracking Issue

### ISSUE THREAD

**Issue by eyusufatik** [chainwayxyz/citrea#1281]
## Prover
- [ ] Risc0 Bonsai adapter cycle budget checks 
- [ ] Parallel proof production
- [ ] Better session recovery
- [ ] RPC for manual proof production, in case we need to hand trigger stuff
- [ ] Local proving on GPUs
- [ ] Multi prover
	- [ ] SP1 adapter
	- [ ] SP1 guest codes
	- [ ] Full node support for multi proof system
	- [ ] Light client supports multi proof system -- this one's hard

## Common (sequencer, full node, prover)
- [x] Structured concurrency
- [x] Graceful shutdown and no storage problems
- [ ] P2P layer for soft confirmations -- we’ll stop using RPC for getSoftConfirmation
  - [ ] Create P2P service crate, runners init this
  - [ ] Fetch soft confirmations through P2P network pipeline
  - [ ] (?) Mempool propagation 
  - [ ] (?) Activate mempool RPC’s

- [ ] Citrea/Clementine/Bridge backend shared e2e testing framework
- [ ] Retreive configs from env if .toml is not present -- helps a lot in deployment/docker
- [ ] Upgrade dependencies (risc0, reth, alloy etc)
- [ ] Profiling / metrics stuff for all nodes — enable in testnet
- [ ] Grafana dashboard for network and nodes — enable in testnet
- [ ] (?) Trusted BitcoinLightClient update as SystemTransactions
- [ ] (?) #1008 

## Full node
- [ ] Pruning and it's subissues (@rakanalh pls add to here, wether existing issues or things you have in mind)
- [ ] Light client proof verification and necessary RPC's 

## Bitcoin DA
- [ ] RBF for Bitcoin transactions (post transaction monitoring) -- maybe CPFP because of chaining
- [ ] Chunks does not need chaining -- @ekrembal  says they might need this property
- [ ] Better tx mining -- takes too much time for prover on big txs
- [ ] Use mempool.space fee calculation

## EVM
- [ ] (?) Offchain contracts
- [ ] Cancun upgrade -- so that we get rid of selfdestruct. Have to think about blobs?
- [ ] Calculate statistic for brotli compression and charge user accordingly

## State Diffs
- [ ] Decide on on-circuit or off-circuit conversion -- this changes light client proof a lot
- [ ] Decide on statefull / stateless state diffs

## Batch Proof
- [ ] Some things regarding soft confirmations are not checked, hashes are not calculated but assumed from the input field
- [ ] Patching ecdsa and keccak 256 crates -- immediate fork, need to do ASAP too
- [ ] #994

## Light Client Proof
Some implementation already at `esad/light-client-starter`
- [x] Decide on circuit inputs/outputs
  - [ ] Update with state diff decision
- [x] Extract light client namespace inclusion & completeness proofs -- chunk parts cause problems here
- [ ] Implement guest side proof verification (`ZkVm` or `ZkVmGuest` trait actually supports this) 
- [ ] Build pipeline -- light client depends on batch proof verification key (can be an input as well), forks?
- [ ] Create light client prover

## Blockscout
- [ ] Revisit fee calc on the backend.
- [ ] Block fees show up wrong (burn meter and amount)
- [ ] Indexing of base fee vault and L1 fee vault are wrong, and they don't show up on state section of a tx
