### ISSUE TITLE
Write a test for offchain storage

### ISSUE THREAD

**Issue by rakanalh** [chainwayxyz/citrea#1458]
# TODO

- [x] Deploy contract prior to a fork
- [x] Activate fork
- [x] First `get_code` RPC returns from state storage
- [x] Second `get_code` RPC returns from offchain
- [x] Deploy a contract post-fork
- [x] Execute a transaction on deployed contract
