### ISSUE TITLE
Flaky tests tracker

### ISSUE THREAD

**Issue by rakanalh** [chainwayxyz/citrea#1614]
- [ ] `FLAKY 2/3 [ 336.947s] citrea::all_tests bitcoin_e2e::batch_prover_test::basic_prover_test`
- [ ] `FLAKY 2/3 [   6.869s] citrea::all_tests bitcoin_e2e::sequencer_test::test_sequencer_missed_da_blocks`
- [ ] `FLAKY 2/3 [ 332.328s] citrea::all_tests e2e::test_offchain_contract_storage`
- [ ] `FLAKY 2/3 [  80.773s] citrea::all_tests evm::fee::test_minimum_base_fee`
- [ ] `TRY 3 FAIL [ 253.667s] citrea::all_tests bitcoin_e2e::batch_prover_test::prover_skips_preproven_commitments_test`
- [ ] `TRY 2 SLOW [>180.000s] citrea::all_tests bitcoin_e2e::light_client_test::test_light_client_proving`
- [ ] `TRY 1 FAIL [ 382.885s] citrea::all_tests bitcoin_e2e::light_client_test::test_light_client_proving_multiple_proofs`

**Comment by jfldde** [comment]
Got a bit out of hand, looking at it.

**Comment by rakanalh** [comment]
I am building up the list as observed from CI runs

**Comment by jfldde** [comment]
Related #1369  #1371 #1396 #1397 #1398 #1406 #1552 #1553 
To be re-assessed as some are quite old and might have been fixed by the latest changes in #1615

**Comment by jfldde** [comment]
https://github.com/chainwayxyz/citrea/actions/runs/20128860585/job/57765031177
