### ISSUE TITLE
EVM: Add L1 fee to `eth_call` and other RPCs

### ISSUE THREAD

**Issue by eyusufatik** [chainwayxyz/citrea#241]
RPCs that need updating:

- [x] eth_getBlockByHash and eth_getBlockByNumber (depends on #245)
- [x] eth_getTransactionReceipt
- [ ] debug_transaction (not quiet sure #244 probably introduced an implementation for this)

**Comment by eyusufatik** [comment]
**Updates**

_Simulation_ RPCs we have and if they include fees in their inspection:
- `eth_call`: disable eip3607, base fee, don't disable block gas limit, Disables L1 fees. -- seems to be the same with reth except we are not disabling block gas limit.
- `eth_estimateGas`: disable eip3607, base fee, don't disable block gas limit -- seems to be the same with reth. Disables L1 fees.
- `eth_createAccessList`: disable eip3607, base fee, don't disable block gas limit, disables L1 fees.
- `debug_traceTransaction`,`debug_traceBlockByNumber`,`debug_traceBlockByHash`: disable eip3607, base fee, don't disable block gas limit, doesn't disable L1 fees.

**Notes while investigating**
- Disableing block gas limit in `eth_call` and `eth_accessList` is ok. We don't do that and limit the simulation with block gas limit. We should either set a higher gas limit or disable it completely and then timeout.
- `debug_trace` endpoints should replay the transactions exactly the way they are executed in blocks. We have should fix the following:
  - Don't disable eip3607 and base fee.  



**TODOs**
- [ ] Decide whether or not to disable block gas limit in above mentioned RPCs. If we're not disabling, we should increase the gas limit.
- [ ] `debug_trace..` endpoints should not disable those things. Replay txs exactly the same in the blocks.

**Comment by eyusufatik** [comment]
We still need an RPC to estimate diffSize so that everybody can be more sure that their transactions will work.

Will create an issue for that.
