### ISSUE TITLE
Devnet Tracking Issue

### ISSUE THREAD

**Issue by eyusufatik** [chainwayxyz/citrea#419]
We are very close to making our testnet targets.

Following are what features and enhancements to be done urgently:

- [x] Proving soft confirmation batches. And prover node related implementations. (will add details)
  - [x] Provable `citrea-stf`
  - [x] Connnecting our prover process with risc0 (ParallelProverService, StateTransitionRuner)
  - [x] Diff format. Probably will just use working_set diff.
  - [x] Sending proof and state diffs to DA layer.
  - [ ] Tests
- [x] DevOps -- @Chinacolt is working on this, plan is ready.
- [x] L1 fee rate related tasks
  - [x] Estimations so that txs don't fail #417 and #420
  - [x] Sequencer can't know a tx fails by not enough balance for L1 fees #409 -- maybe we can modify mempool to account for L1 fees, but this will be a little resource heavy. Or #477 ensuring we run them only once. (enough for devnet)
  - [ ] Deviding L1 fees between transactions. #267 -- This can be a hard fork post testnet launch.
- [x] Full node to sequencer transition -- in case of failure a full node we run can take over as sequencer, but it should know any pending sequencer commitments, everything else should work without block loss. #443 
- [x] Activating the bridge #403 
  - [x] Write tests for deposit transactions
  - [ ] E2E test for deposit transactions (might not work with mock-da we'll see)
- [ ] Ethereum foundation tests. @rakanalh is working on this but there are a lot of cases reth doesn't run, we'll need to implement those cases on our own.
- [x] Writing a seperate pool for deposit transactions in mempool.
- [x] Handling multiple commitments per DA block #189 -- this is really easy.
- [x] Making blockscout ready for deployment. Things work right now, should set genesis and set branding.
- [ ] Support reorgs in full nodes. This shouldn't happen, but we must implement this nevertheless. https://github.com/Sovereign-Labs/sovereign-sdk/issues/1023
- [ ] Sequencer main loop enhancements #133 -- Nothing fancy, we should just make our sequencer not miss the 2 second block time.
  - [x] This also means we should be more careful with what we push to our state transition function. #412 
- [x] Better error handling all around -- we are ok imo, but always can do better :)
- [x] Bridge frontend @selinisik 's working on this but to accelerate things we can help.
- [x] Bridge backend @ekrembal and @gwn making really fast progress on this but we should sync regularly esp. for the seperate deposit pool.
- [x] Mempool Dump #478

**Comment by okkothejawa** [comment]
Sorry, misclicked.
