### ISSUE TITLE
Testnet tracking issue

### ISSUE THREAD

**Issue by kpp** [chainwayxyz/citrea#707]
P1 - highest priority (required to launch Testnet)
P2 - medium (required for Testnet but easy to implement)
P3 - lowest (can be done even after launching Testnet)

sov-sdk updates:

- [ ] [P1] - backport storage system updates #734
- [ ] [P1] - fork manager (they have L1, we need L2) - don't need a full fork manager, however being able to revert state is important #736
- [x] [P3] - Async storage read for RPC (already some implementations on our end #528)
- [ ] [P3] - accelerate deps for risc0 (sec256k1 will need accelerator for new version) #710 

Prover:

- [x] [P1] - save witness generated in a database, so sync and generating proofs can be seperated #737
- [x] [P1] - better sync mechanism in the prover. #738
- [x] [P1] - check sequencer commitment diff sizes and guarantee the serialized and compressed diff is under a certain size #739
- [x] [P1] - Bitcoin DA supports chunk transactions with a single commit transaction #744 
- [x] [P2] - use a more performant serialization library (in zk cycles) #751
- [x] [P2] - use Ozan's Bitcoin merkle tree verification #752
- [x] [P2] - update to Risc0 1.0.0 #753
- [x] [P2] - reproducible builds for ZK guest #637 
- [x] [P3] - figure out if a better state diff format can be utilized https://github.com/chainwayxyz/citrea/issues/711
- [ ] [P3] - https://github.com/chainwayxyz/citrea/issues/712
- [x] [P3] - improve cycle counts #713

A new proving system
- [x] [P1] - sequencer constantly tracks diff size, commits when serialized and compressed state diff is close to a certain limit #739
- [x] [P1] - sequencer commits to L2 range not L1-L2 range #748
- [x] [P1] - batch proofs can be done for an array of sequencer commitments inside a Bitcoin block, don't enforce all sequencer commitments #747 

Full node:
- [ ] [P1] - pruning
    - [x] rename rollup config to full node config #728
    - [ ] add config for pruning (how much to store, when to prune) to full node config #729
    - [ ] implement pruning based on rollup config #730
- [x] [P1] - build fetch-apply pipeline for syncing (1 thread to query, 1 thread to apply them)
    - [x] - split L1/L2 sync #741
    - [x] - https://github.com/chainwayxyz/citrea/issues/685
    - [x] - https://github.com/chainwayxyz/citrea/issues/686
- [x] - [P2] - batch query soft confirmations (N instead of 1 by 1) #754

All improvements:

- [x] [P1] - research other state diff rollups regarding how they split L1 fee https://github.com/chainwayxyz/citrea/issues/267
    - [x] make simulations for our case and come up with coefficients
    - [x] implement
- [x] [P1] - Blockscout and batch explorer
    - [x] research rollup mode
    - [x] fees
    - [x] mark sys tx
    - [x] deposits and withdrawals
- [x] [P1] - our own fork spec for all rollup - conditions #235
- [x] [P2] - implement fee accumulator contracts #755
- [ ] [P2] - L1 fee info contracts
- [ ] [P2] - Use L1 fee info contracts in EVM to charge L1 fee
- [x] [P2] - send fees to fee addresses (base/priority/l1 fee addresses -- deploy the fee accumulator contracts on these addresses ) #756
- [x] [P2] - Upgradable bridge (system contracts) #757
- [ ] [P3] - research DA send improvements #714
- [ ] [P3] - implement DA send improvements
- [ ] [P3] - Precompiles (verify bitcoin tx inclusion)
    - [ ] precompiles implementation - bitcoin SPV optimized for zkvm
    - [ ] gas metering for this precompile
- [ ] [P3] - batch explorer that syncs from L1 and Citrea RPC
- [ ] [P3] - research fee-less withdrawals
- [ ] [P4] - have the batch explorer inside blockscout

**Comment by kpp** [comment]
Overridden by https://github.com/chainwayxyz/citrea/issues/832
