### ISSUE TITLE
Testnet Tracking 2

### ISSUE THREAD

**Issue by eyusufatik** [chainwayxyz/citrea#832]
- [x] #1053
- [x] #977 
- [x] #964
- [x] #965 
- [x] #967  (low priority)
- [x] #954  (low priority)
- [x] #966 
- [ ] #710 
- [ ] DA improvements
  - [x] DA supports chunks #925 
  - [x] DA supports versions #912 
  - [x] #971 
  - [x] #972 
  - [x] #970  (low priority)
  - [ ] #892  (low priority)
  - [x] #1002 
- [x] #737 
- [x] #738 
- [x] #739 
- [x] #751 
- [x] #637 
- [x] #748 
- [x] #235 
- [x] #756 
- [x] #833 
- [x] #856 
- [x] #858 
- [x] #859 
- [x] Blockscout must-haves
  - [x] Correct fee calc.
  - [x] System tx marker
- [x] #528 
- [x] #753 
- [x] #728 
- [x] #741 
- [x] #685 
- [x] #686 
- [x] #754 
- [x] #755 
- [x] #757 

### Would be hard to pull off after launching testnet

These are issues we need to decide if we are gonna implement or not.
If want to do these, we have to do it before testnet or else it would need a hard fork to implement.
- [x] #1007
- [ ] ~#1024~ 
- [x] #1015 
- [x] #1004
- [x] #999
- [ ] #1008 
- [ ] #996 
- [ ] #994 
- [x] #1041
