### ISSUE TITLE
Meta: Optimize guest code cycles

### ISSUE THREAD

**Issue by yaziciahmet** [chainwayxyz/citrea#945]
Go through the guest code to find potential optimizations, and implement them.

**Achievable:**
Much lower cycle counts.

- [x] https://github.com/chainwayxyz/citrea/issues/751
- [x] https://github.com/chainwayxyz/citrea/issues/876
- [x] https://github.com/chainwayxyz/citrea/pull/968
- [x] https://github.com/chainwayxyz/citrea/pull/933
- [x] https://github.com/chainwayxyz/citrea/pull/959
- [x] https://github.com/chainwayxyz/citrea/issues/952

**Comment by rakanalh** [comment]
@eyusufatik Every single sub-issue here was done. Shall we close this one?
